//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityBase } from '../../EFCoreBase/Entities/EntityBase';
import { Lawyer } from '../Entities/Lawyer';
import { Client } from '../Entities/Client';
import { CasePart } from '../Entities/CasePart';
import { CourtType } from '../Enums/CourtType';

export class CaseDto extends EntityBase
{
	public managerLawyer: Lawyer;
	public client: Client;
	public participants: CasePart[];
	public districtName: string;
	public courtAffairNumber: string;
	public caseNumber: string;
	public courtType: CourtType;
	public courtNumber: number;
}
