//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityBase } from '../../EFCoreBase/Entities/EntityBase';
import { Lawyer } from '../Entities/Lawyer';
import { Client } from '../Entities/Client';
import { CasePart } from '../Entities/CasePart';
import { CourtMemberBase } from '../Entities/BaseEntities/CourtMemberBase';
import { ChamberNames } from '../Enums/ChamberNames';
import { CourtTypes } from '../Enums/CourtTypes';

export class CaseDto extends EntityBase
{
	public managerLawyer: Lawyer;
	public client: Client;
	public participants: CasePart[];
	public plaintiff: CourtMemberBase;
	public defender: CourtMemberBase;
	public notifiableMembers: CasePart[];
	public districtName: string;
	public courtAffairNumber: string;
	public caseNumber: string;
	public chamberName: ChamberNames;
	public courtTypes: CourtTypes;
	public courtNumber: number;
	public GetFormattedCaseNames() : string
	{
		return null;
	}
	public GetPlaintiffAndDefender() : [CourtMemberBase,CourtMemberBase]
	{
		return null;
	}
}
