//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CaseDto } from './CaseDto';
import { Client } from '../Entities/Client';

export class CasesContext
{
	public cases: CaseDto[];
	public clients: Client[];
}
