//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CourtType } from '../Enums/CourtType';
import { Client } from '../Entities/Client';
import { CourtMemberBase } from '../Entities/BaseEntities/CourtMemberBase';

export class FileDto
{
	public caseNumber: string;
	public courtType: CourtType;
	public currentLawyersClient: Client;
	public courtMembers: CourtMemberBase[];
}
