//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum CourtRoles {
	Intimated = 0,
	PutInCause = 1,
	Plaintiff = 2,
	Defender = 3,
	PlaintiffLawyer = 4,
	DefenderLawyer = 5
}
