//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IRequestResult } from '../../Interfaces/IRequestResult';
import { RequestResultTypes } from '../../Enums/RequestResultTypes';

export class FailedLogin implements IRequestResult
{
	public message: string;
	public messageMessage: string;
	public result: RequestResultTypes;
}
