//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityBase } from '../../EFCoreBase/Entities/EntityBase';
import { RoleTypes } from './RoleTypes';
import { UserRole } from './UserRole';

export class Role extends EntityBase
{
	public roleType: RoleTypes;
	public userRoles: UserRole[];
}
