//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityBase } from '../../EFCoreBase/Entities/EntityBase';
import { UserRole } from './UserRole';
import { RoleTypes } from './RoleTypes';

export class User extends EntityBase
{
	public name: string;
	public hashedPassword: string;
	public userRoles: UserRole[];
	public roles: RoleTypes[];
}
