//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { MyOtherClass } from './MyOtherClass';

export class MyModel
{
	public name: string;
	public description: string;
	public caca: MyOtherClass;
}
