import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AxiosProvider } from './Contexts/Slices/AxiosContext'
import ProvidersContainer from './Components/ProvidersContainer'
import { useState } from 'react'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LawyerApp :)',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="dark">
      <body>
        <ProvidersContainer>
          {children}

        </ProvidersContainer>
      </body>

    </html>
  )
}
