import "./globals.css";
import type { Metadata } from "next";

import ThemeRegistry from "../../LogicFiles/MUIStuff/ThemeRegistry";
import Providers from "../../LogicFiles/Redux/Providers";

export const metadata: Metadata = {
    title: "LawyerApp :)",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: { children: React.ReactNode }) {

    return (
        <html lang="en">
            <body>
                <div>
                    {/* tjrs use /rem ou viewport pour que ca scale mieux in and out */}
                    {/* <Box sx={{ backgroundColor: 'black', width: '100vw', height: '100vh' }}>. */}
                    <ThemeRegistry>
                        <Providers>
                                {children}
                        </Providers>
                    </ThemeRegistry>
                    {/* </Box> */}
                </div>
            </body>
        </html>
    );
}
