import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AxiosProvider } from './Contexts/AxiosSlice/AxiosContext'
import ProvidersContainer from './Components/ProvidersContainer'
import { useState } from 'react'
import Providers from './Redux/Providers'
// const inter = Inter({ subsets: ['latin'] })
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Box, Container, ThemeProvider, createTheme } from '@mui/material'
import { brown, orange } from '@mui/material/colors'
import { palette } from '@mui/system';
import ThemeRegistry from './MUIStuff/ThemeRegistry'


export const metadata: Metadata = {
  title: 'LawyerApp :)',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en" >
      <body>
        <div>
          {/* tjrs use /rem ou viewport pour que ca scale mieux in and out */}
          {/* <Box sx={{ backgroundColor: 'black', width: '100vw', height: '100vh' }}>. */}
          <ThemeRegistry>
            <Providers>
              <ProvidersContainer>
                {children}
              </ProvidersContainer>
            </Providers>
          </ThemeRegistry>
          {/* </Box> */}
        </div>
      </body>
    </html>
  )
}
