//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class CasesEndpoints
{
	static path: string = "case";
	static createNewCase: string = `${CasesEndpoints.path}/createnewcase`;
	static getCasesContext: string = `${CasesEndpoints.path}/getcasescontext`;
	static saveContextDto: string = `${CasesEndpoints.path}/savecontextdto`;
}
