//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class UserEndpoints
{
	static path: string = "user";
	static credentialsLogin: string = `${UserEndpoints.path}/credentialslogin`;
	static tokenLogin: string = `${UserEndpoints.path}/tokenlogin`;
	static register: string = `${UserEndpoints.path}/register`;
	static multipleParamTest: string = `${UserEndpoints.path}/multipleparamtest`;
}
