//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class CaseCreationInfo
{
	public lawyerId: string;
	public caseNumber: string;
	public clientFirstName: string;
	public clientLastName: string;
}
