//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CourtMemberBase } from './BaseEntities/CourtMemberBase';
import { Case } from '../../EFCoreBase/Entities/Case';

export class CasePart extends CourtMemberBase
{
	public caseId: string;
	public case: Case;
}
