//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CourtMemberBase } from './BaseEntities/CourtMemberBase';
import { User } from '../Authentication/User';
import { Case } from '../../EFCoreBase/Entities/Case';
import { Client } from './Client';

export class Lawyer extends CourtMemberBase
{
	public userId: string;
	public user: User;
	public courtLockerNumber: string;
	public cases: Case[];
	public clients: Client[];
}
