//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { RoleTypes } from '../RoleTypes';

export class RegisterRequest
{
	public username: string;
	public password: string;
	public role: RoleTypes;
}
