//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IRequestResult } from '../../Interfaces/IRequestResult';
import { UserDto } from '../UserDto';

export class SuccessLoginResult implements IRequestResult
{
	public userDto: UserDto;
	public token: string;
	public loginResultTypes: number;
}
