//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityBase } from './EntityBase';
import { Lawyer } from '../../ProcedureMakerServer/Entities/Lawyer';
import { Client } from '../../ProcedureMakerServer/Entities/Client';
import { CasePart } from '../../ProcedureMakerServer/Entities/CasePart';
import { ChamberNames } from '../../ProcedureMakerServer/Enums/ChamberNames';

export class Case extends EntityBase
{
	public managerLawyerId: string;
	public managerLawyer?: Lawyer;
	public clientId: string;
	public client: Client;
	public participants: CasePart[];
	public accountStatement: any;
	public districtName: string;
	public courtAffairNumber: string;
	public caseNumber: string;
	public courtType: ChamberNames;
	public courtNumber: number;
}
