//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export abstract class EntityBase
{
	public id: string;
	public Equals(obj?: any) : boolean
	{
		return null;
	}
	public Equals(other?: any) : boolean
	{
		return null;
	}
	public GetHashCode() : number
	{
		return null;
	}
	public GenerateIdIfNull() : any
	{
		return null;
	}
	public CompareIds(other: EntityBase) : boolean
	{
		return null;
	}
}
