//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { PersonBase } from './PersonBase';
import { CourtRoles } from '../../Enums/CourtRoles';

export abstract class CourtMemberBase extends PersonBase
{
	public notificationEmail: string;
	public courtRole: CourtRoles;
	public isNotifiable: boolean;
	public GetGenderedCourtRoleName() : string
	{
		return null;
	}
}
